# Generated by Django 5.0.3 on 2024-03-15 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabandesk', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='owner',
        ),
        migrations.AddField(
            model_name='task',
            name='table',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, to='kabandesk.table'),
        ),
    ]
