# Generated by Django 5.0.3 on 2024-03-28 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kabandesk', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='status',
            new_name='state',
        ),
    ]
