# Generated by Django 5.0.3 on 2024-03-31 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kabandesk', '0002_rename_status_task_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(db_index=True, default='', max_length=254),
        ),
    ]
